# Site
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sandeep Borhade
title: Senior Full Stack Engineer
email: sandeephborhade@gmail.com
website: www.github.com/sborhade

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: shborhade
github_username:  sborhade
instagram_username: jameswgrant
linkedin_username: sandeephb

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
